[package]
name = "apt-updater-plus-logging"
version = "0.1.0"
edition = "2024"

[dependencies]
better-logger = { version = "2.0.1", features = ["native"] }
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"